### ISSUE TITLE
Error in response

### ISSUE THREAD

**Issue by DavidNingthou** [tuhinpal/imdb-api#12]
Hello i am getting the error below when using both your example url and also mine. please any solution?

{"query":null,"results":[],"message":"Unexpected token 'T', \"Too many n\"... is not valid JSON"}

**Comment by tuhinpal** [comment]
Too many request, and amazon block the request. Try again in one day. Also you can directly call https://github.com/tuhinpal/imdb-api/blob/master/src/routes/search.js#L11 imdb search.

**Comment by DavidNingthou** [comment]
I've integrated a search feature on my app using your awesome code. Now that it's giving errors, how can I mitigate such issues in future? I don't know much about this things

**Comment by tuhinpal** [comment]
Deploy your own worker can resolve this issue. After deployment attach it with a domain to configure cache. If your cache is working, there is low chance you will encounter it again.

If there is any feature which will do an API request when user type something, you maybe remove that feature.

**Comment by tuhinpal** [comment]
https://github.com/tuhinpal/imdb-api/blob/master/src/routes/search.js#L11

Again, check this code to create an wrapper which will directly call IMDB.

**Comment by tuhinpal** [comment]
Feel free to reopen this issue if needed.
