### ISSUE TITLE
How to use the new cache?

### ISSUE THREAD

**Issue by joinemm** [tuhinpal/imdb-api#13]
I updated my fork with your new changes and the kv cache no longer works. I see you updated to use some other cache but I can't figure out how to use it. Getting a lot of non-json responses and errors due to the requests not being cached properly

**Comment by tuhinpal** [comment]
Park you worker in a domain.

**Comment by joinemm** [comment]
so do I need to buy a domain name just to have cache?

**Comment by tuhinpal** [comment]
No you don't need to buy. Use freenom.

KV cache was limited, that's why used cloudflare builtin cache.

To use cloudflare builtin cache, you need to setup a domain.

**Comment by tuhinpal** [comment]
Feel free to reopen if needed.
