### ISSUE TITLE
/title API fails with "Worker exceeded resource limits" every time

### ISSUE THREAD

**Issue by u9g** [tuhinpal/imdb-api#14]
Hi, thanks for making this project. Unfortunately after deploying to cloudflare workers, when using the /title endpoint, I seem to get "Worker exceeded resource limits" every time. Here's an example with the url I tried: `https://imdb-api.aibotted849.workers.dev/title/tt6522580`. It seems to happen 90% of the time with the worker in the readme too.

**Comment by tuhinpal** [comment]
Cloudflare provides you 1lakh execution per day, this means your limit is
reached. You can upgrade your plan!

**Comment by u9g** [comment]
> 1lakh

My execution limit is not reached 
![image](https://user-images.githubusercontent.com/43508353/225964498-c308e7df-b41e-4f0d-96d9-994fa3acf7c5.png)

The individual request seems to be exceeding the allowed cpu usage per request 
![image](https://user-images.githubusercontent.com/43508353/225964806-4451b90d-af65-428f-b822-a3e6ff82b7a8.png)

**Comment by tuhinpal** [comment]
The link you provided seems to be working now, you can configure cache to
save resources. I will deep dive into the problem soon.
