### ISSUE TITLE
Run in docker seems to have stopped randomly

### ISSUE THREAD

**Issue by u9g** [tuhinpal/imdb-api#15]
Hi, I was running the docker container, except it seems to have exited with code 137, here's the logs I have: https://gist.github.com/u9g/7334334620c1ab42be54b6b865a53827 , any info on why this happened? I'm opened to more logs if that can help find the crash.

**Comment by tuhinpal** [comment]
Seems like working 🤔

**Comment by u9g** [comment]
Seems fine now, thanks anyway
