### ISSUE TITLE
Cloudflare deployment issues

### ISSUE THREAD

**Issue by ninoskuflic** [tuhinpal/imdb-api#4]
Hi,
whenever I'm trying to do a deployment to Cloudflare, I get "Project had an error" on https://deploy.workers.cloudflare.com/.

**Comment by tuhinpal** [comment]
Kindly raise the issue to Cloudflare team

**Comment by ninoskuflic** [comment]
I see that when trying to deploy to Cloudflare Workers, I get the following error: "Project had an error".

**Comment by dmix** [comment]
I'm also experiencing this. The Cloudflare deploy page just gives a generic "Error"

Is there some fields missing in `deploy.yml` or something?

I checked dev console and I see cloudflare is trying to do an HTTP request to a Github URL that has "undefined" where it should be my github username and deploy.yml

I've also made a Cloudflare community post to get help https://community.cloudflare.com/t/deploying-a-worker-imdb-api-gives-me-a-generic-error-message/449663

<img width="1506" alt="Screenshot 2023-01-04 at 12 54 13 PM" src="https://user-images.githubusercontent.com/12528/210621140-712d8f48-19ff-4813-9b2d-b87803383350.png">

<img width="1115" alt="Screenshot 2023-01-04 at 12 54 00 PM" src="https://user-images.githubusercontent.com/12528/210621138-e950bacd-6e20-4236-b6db-73548e355430.png">

<img width="1109" alt="Screenshot 2023-01-04 at 12 53 47 PM" src="https://user-images.githubusercontent.com/12528/210621130-e32b9978-36d6-4971-8d8b-5fb2c3318cf6.png">

**Comment by dmix** [comment]
for the record I just manually got it working using the `wrangler cli`, the helper link just didnt work

**Comment by tuhinpal** [comment]
Hello @ninoskuflic @dmix, can you guys try the same now?

**Comment by tuhinpal** [comment]
Feel free to reopen this issue if needed.
