### ISSUE TITLE
Title endpoint not working.

### ISSUE THREAD

**Issue by T1b4lt** [tuhinpal/imdb-api#5]
Using the same example that is in the README:

[https://imdb-api.tprojects.workers.dev/title/tt6522580](https://imdb-api.tprojects.workers.dev/title/tt6522580)

It returns the following error:
`{"message":"Cannot read properties of undefined (reading 'innerHTML')"}`

**Comment by tuhinpal** [comment]
Fixed by https://github.com/tuhinpal/imdb-api/commit/2c313f9ae45675d8438d6d6e8f7d92297fc8db53
