### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by SpEcHiDe** [tuhinpal/imdb-api#6]
When I try the https://imdb-api.tprojects.workers.dev/search?query=Little%20Things (mentioned in the README), I get the following response `{"query":null,"results":[],"message":"Cannot read properties of undefined (reading 'childNodes')"}`.

**Comment by tuhinpal** [comment]
Possibly fixed by https://github.com/tuhinpal/imdb-api/commit/1aa2e6c62ab77bb121a90e8498836b772249a9cd this.

**Comment by tuhinpal** [comment]
Sometimes, IMDB is blocking request.

**Comment by SpEcHiDe** [comment]
Ok, thank you 🙏👍

**Comment by tuhinpal** [comment]
Now it will work fine by https://github.com/tuhinpal/imdb-api/commit/f59bfa55ff8358d4340f79890f544127bcdc4cf1
